### ISSUE TITLE
AeroFC firmware version = unknown

### ISSUE THREAD

**Issue by anselmolsm** [intel-aero/packages#37]
Originally reported at https://github.com/intel-aero/meta-intel-aero/issues/291#issuecomment-365993160

> sudo aerofc-get-version.py" outputs "aerofc-get-version.py: command not found

srnetsr, could you please check the version of aero-utils installed?

**Comment by anselmolsm** [comment]
OK, it was fixed in aero-utils 0.1-8 but the deb in the repo is still 0.1-7.

**Comment by gitsr-sys** [comment]
Hi, I really appreciate it.

I do not understand what is aero-utils..

I installed yocto before by following https://github.com/intel-aero/meta-intel-aero/wiki/02-Initial-Setup
I downloaded .iso from https://downloadcenter.intel.com/download/27399/Intel-Aero-Platform-for-UAVs-Installation-Files?v=t

and now I am trying to use ubuntu and ros..so following https://github.com/intel-aero/meta-intel-aero/wiki/90-(References)-OS-user-Installation
By following the above link,
I just run the following commands
```
echo 'deb https://download.01.org/aero/deb xenial main' | sudo tee /etc/apt/sources.list.d/intel-aero.list
wget -qO - https://download.01.org/aero/deb/intel-aero-deb.key | sudo apt-key add -
sudo apt-get update
sudo apt-get upgrade
sudo apt-get -y install gstreamer-1.0 libgstreamer-plugins-base1.0-dev libgstrtspserver-1.0-dev gstreamer1.0-vaapi gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-libav ffmpeg v4l-utils python-pip
sudo pip install pymavlink
sudo apt-get -y install aero-system
sudo reboot
```

**Comment by gitsr-sys** [comment]
Now I backed to yocto...
In terminal, I can see
aero-get-version.py outputs AeroFC firmware version = 1.6.5
In addition, I can find "aero-fc-get-version.py" file...

Now I am going to install ubuntu 16.04 for ros...

What should I do for keeping the files..

**Comment by anselmolsm** [comment]
This issue happens only with the packages for Ubuntu, it has nothing to do with yocto. Fix is on the way, hold on.

**Comment by anselmolsm** [comment]
Repo updated.
If you had the Ubuntu system installed, `apt-get update && apt-get upgrade` would be enough.
As you are reinstalling the whole system, [follow the steps you've been following ](https://github.com/intel-aero/packages/issues/37#issuecomment-366086552) and it will install the new package. Then, please repeat the tests and post the results.

**Comment by gitsr-sys** [comment]
Thank you for all your support, @anselmolsm !!
I am reinstall ubuntu and doing all the steps.

However, I have one question about python version.

Do I need to do
$ sudo apt-get -y install python-pip
or
<del>$ sudo apt-get -y install python3-pip</del>
or
<del>both?</del>

**Comment by anselmolsm** [comment]
~As far as I understand only python3-pip (which installs pip3).~

**Comment by gitsr-sys** [comment]
So, I did

```
$ echo 'deb https://download.01.org/aero/deb xenial main' | sudo tee /etc/apt/sources.list.d/intel-aero.list
$ wget -qO - https://download.01.org/aero/deb/intel-aero-deb.key | sudo apt-key add -
$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt-get -y install gstreamer-1.0 libgstreamer-plugins-base1.0-dev libgstrtspserver-1.0-dev gstreamer1.0-vaapi gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-libav ffmpeg v4l-utils
```
(I did not install python-pip at here)
and installed python3-pip as shown in the following.
```
$ sudo apt-get -y install python3-pip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following additional packages will be installed:
  libexpat1-dev libpython3-dev libpython3.5-dev python-pip-whl python3-dev
  python3-setuptools python3-wheel python3.5-dev
Suggested packages:
  python-setuptools-doc
The following NEW packages will be installed:
  libexpat1-dev libpython3-dev libpython3.5-dev python-pip-whl python3-dev
  python3-pip python3-setuptools python3-wheel python3.5-dev
0 upgraded, 9 newly installed, 0 to remove and 11 not upgraded.
Need to get 39.2 MB of archives.
After this operation, 57.3 MB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libexpat1-dev amd64 2.1.0-7ubuntu0.16.04.3 [115 kB]
Get:2 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 libpython3.5-dev amd64 3.5.2-2ubuntu0~16.04.4 [37.3 MB]
Get:3 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 libpython3-dev amd64 3.5.1-3 [6,926 B]
Get:4 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 python-pip-whl all 8.1.1-2ubuntu0.4 [1,110 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 python3.5-dev amd64 3.5.2-2ubuntu0~16.04.4 [413 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 python3-dev amd64 3.5.1-3 [1,186 B]
Get:7 http://us.archive.ubuntu.com/ubuntu xenial-updates/universe amd64 python3-pip all 8.1.1-2ubuntu0.4 [109 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 python3-setuptools all 20.7.0-1 [88.0 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 python3-wheel all 0.29.0-1 [48.1 kB]
Fetched 39.2 MB in 5s (7,176 kB/s)  
Selecting previously unselected package libexpat1-dev:amd64.
(Reading database ... 178293 files and directories currently installed.)
Preparing to unpack .../libexpat1-dev_2.1.0-7ubuntu0.16.04.3_amd64.deb ...
Unpacking libexpat1-dev:amd64 (2.1.0-7ubuntu0.16.04.3) ...
Selecting previously unselected package libpython3.5-dev:amd64.
Preparing to unpack .../libpython3.5-dev_3.5.2-2ubuntu0~16.04.4_amd64.deb ...
Unpacking libpython3.5-dev:amd64 (3.5.2-2ubuntu0~16.04.4) ...
Selecting previously unselected package libpython3-dev:amd64.
Preparing to unpack .../libpython3-dev_3.5.1-3_amd64.deb ...
Unpacking libpython3-dev:amd64 (3.5.1-3) ...
Selecting previously unselected package python-pip-whl.
Preparing to unpack .../python-pip-whl_8.1.1-2ubuntu0.4_all.deb ...
Unpacking python-pip-whl (8.1.1-2ubuntu0.4) ...
Selecting previously unselected package python3.5-dev.
Preparing to unpack .../python3.5-dev_3.5.2-2ubuntu0~16.04.4_amd64.deb ...
Unpacking python3.5-dev (3.5.2-2ubuntu0~16.04.4) ...
Selecting previously unselected package python3-dev.
Preparing to unpack .../python3-dev_3.5.1-3_amd64.deb ...
Unpacking python3-dev (3.5.1-3) ...
Selecting previously unselected package python3-pip.
Preparing to unpack .../python3-pip_8.1.1-2ubuntu0.4_all.deb ...
Unpacking python3-pip (8.1.1-2ubuntu0.4) ...
Selecting previously unselected package python3-setuptools.
Preparing to unpack .../python3-setuptools_20.7.0-1_all.deb ...
Unpacking python3-setuptools (20.7.0-1) ...
Selecting previously unselected package python3-wheel.
Preparing to unpack .../python3-wheel_0.29.0-1_all.deb ...
Unpacking python3-wheel (0.29.0-1) ...
Processing triggers for doc-base (0.10.7) ...
Processing 1 added doc-base file...
Processing triggers for man-db (2.7.5-1) ...
Setting up libexpat1-dev:amd64 (2.1.0-7ubuntu0.16.04.3) ...
Setting up libpython3.5-dev:amd64 (3.5.2-2ubuntu0~16.04.4) ...
Setting up libpython3-dev:amd64 (3.5.1-3) ...
Setting up python-pip-whl (8.1.1-2ubuntu0.4) ...
Setting up python3.5-dev (3.5.2-2ubuntu0~16.04.4) ...
Setting up python3-dev (3.5.1-3) ...
Setting up python3-pip (8.1.1-2ubuntu0.4) ...
Setting up python3-setuptools (20.7.0-1) ...
Setting up python3-wheel (0.29.0-1) ...
```
Here, I tried to installed pymavlink...
```
$ sudo -H pip3 install pymavlink
Collecting pymavlink
  Downloading pymavlink-2.2.8.tar.gz (3.0MB)
    100% |████████████████████████████████| 3.0MB 261kB/s
Collecting future (from pymavlink)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |████████████████████████████████| 829kB 809kB/s
Requirement already satisfied (use --upgrade to upgrade): lxml in /usr/lib/python3/dist-packages (from pymavlink)
Building wheels for collected packages: pymavlink, future
  Running setup.py bdist_wheel for pymavlink ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-10l682me/pymavlink/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpo5raqvqipip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  running build_py
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-10l682me/pymavlink/setup.py", line 160, in <module>
      ext_modules = extensions
    File "/usr/lib/python3.5/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.5/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 179, in run
      self.run_command('build')
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.5/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.5/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.5/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-10l682me/pymavlink/setup.py", line 93, in run
      generate_content()
    File "/tmp/pip-build-10l682me/pymavlink/setup.py", line 21, in generate_content
      from generator import mavgen, mavparse
    File "/tmp/pip-build-10l682me/pymavlink/generator/mavgen.py", line 12, in <module>
      from future import standard_library
  ImportError: No module named 'future'
 
  ----------------------------------------
  Failed building wheel for pymavlink
  Running setup.py clean for pymavlink
  Running setup.py bdist_wheel for future ... done
  Stored in directory: /root/.cache/pip/wheels/c2/50/7c/0d83b4baac4f63ff7a765bd16390d2ab43c93587fac9d6017a
Successfully built future
Failed to build pymavlink
Installing collected packages: future, pymavlink
  Running setup.py install for pymavlink ... done
Successfully installed future-0.16.0 pymavlink-2.2.8
You are using pip version 8.1.1, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
I tried to confirm whether pymavlink is installed correctly or not...
```
$ sudo -H pip3 install pymavlink
Requirement already satisfied (use --upgrade to upgrade): pymavlink in /usr/local/lib/python3.5/dist-packages
Requirement already satisfied (use --upgrade to upgrade): future in /usr/local/lib/python3.5/dist-packages (from pymavlink)
Requirement already satisfied (use --upgrade to upgrade): lxml in /usr/lib/python3/dist-packages (from pymavlink)
```
```
$ sudo apt-get -y install aero-system
$ sudo reboot
```

Now I can find "aerofc-get-version.py" file in the computer.

I got the outputs of "sudo aero-get-version.py" as the following
AeroFC firmware version = unknown

I think pymavlink was not installed correctly with python3-pip...
I will figure it out to install it correctly....

**Comment by gitsr-sys** [comment]
I tried all method to install pymavlink...and finally found the solution.

**1.** tried both python3-pip and python-pip
I used python3-pip to install pymavlink, sudo -H pip3 install pymavlink, but I got the error that "import error: no module named 'future'"
I thought I need to install future with python-pip. So I did `$ sudo -H pip install future`
and then, I did `$ sudo -H pip3 install pymavlink` again.
However, it did not seem to be successful.
Because the output of `$ sudo aero-get-version.py` is "fc = unknown"

So, I tried to use python-pip for installing pymavlink with the following command.
`$ sudo -H pip install pymavlink`
and
`$ sudo aero-get-version.py` showed the right output, "fc = 1.6.5"


**2.** **Solution** - use only python-pip
I reinstalled ubuntu 16.04 to confirm that installing only "python-pip" will work to install pymavlink.
And just executed the following commands from [https://github.com/intel-aero/meta-intel-aero/wiki/90-(References)-OS-user-Installation](url).
```
$ echo 'deb https://download.01.org/aero/deb xenial main' | sudo tee /etc/apt/sources.list.d/intel-aero.list
$ wget -qO - https://download.01.org/aero/deb/intel-aero-deb.key | sudo apt-key add -
$ sudo apt-get update
$ sudo apt-get upgrade
$ sudo apt-get -y install gstreamer-1.0 libgstreamer-plugins-base1.0-dev libgstrtspserver-1.0-dev gstreamer1.0-vaapi gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-libav ffmpeg v4l-utils python-pip
$ sudo -H pip install pymavlink
```
Here, I installed only python-pip,
and put **-H** in the above command. (can someone check that it works correctly without -H?)
```
$ sudo apt-get -y install aero-system
$ sudo reboot
```
Then, finally I found that `$ sudo aero-get-version.py` outputs "fc = 1.6.5" correctly...

Interestingly, during installation of pymavlink, I can see some error message. But final message said pymavlink is installed successfully. I think do not need to worry about it.


I really appreciate you for helping me to resolve this issue, @anselmolsm !!

p.s. If you can edit your previous posts in here and [https://github.com/intel-aero/meta-intel-aero/issues/291](url), then please remove the comment about pip3. Then, it can avoid confusion.

**Comment by anselmolsm** [comment]
I expected it to use pymavlink installed by pip3 as the script using that runs with python3. Cool that you fixed the problem.
